# Generated by Django 3.2.4 on 2021-07-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0004_rename_bills_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='bill_counter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
