# Generated by Django 3.2.4 on 2021-07-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('income', '0005_bill_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company_name', models.CharField(max_length=120)),
                ('Monthly_salary', models.IntegerField()),
            ],
        ),
    ]
